export const SET_DATA_EMPLOYEES = "SET_DATA_EMPLOYEES";
export const SET_EMPLOYEES = "SET_EMPLOYEES";
export const SET_DEPARTMENTS = "SET_DEPARTMENTS";
export const SET_DESIGNATIONS = "SET_DESIGNATIONS";
export const SET_EMP_MODES = "SET_EMP_MODES";
export const SET_SKILLS = "SET_SKILLS";
export const SET_TABLE_PROPS = "SET_TABLE_PROPS";
export const SET_LOADING = "SET_LOADING";
